packages:
- "core-base-fe"
- "core-jobs-fe"
- "core-versions-fe"
- "core-webhooks-fe"
- "core-accounting-fe"
- "core-comments-fe"
- "core-notifications-fe"
- "core-config-fe"
- "test-core-fe"
- "docs"