# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: versions

  outdated:
    cmds:
      - cmd: bundle outdated
        ignore_error: true
      - cmd: pnpm outdated
        ignore_error: true

  tidy:
    cmds:
      - cmd: bundle exec rubocop '**/*.rb' --format worst
        ignore_error: true
      - cmd: bundle exec rubocop '**/*.rb' --format offenses
        ignore_error: true
      - cmd: npx prettier -c .
        ignore_error: true
      # - cmd: bundle exec rubocop '**/*.rb'
      #   ignore_error: true

  tidy-fix:
    cmds:
      - npx prettier --loglevel warn -w .
      - bundle exec rubocop -a '**/*.rb

  versions:
    silent: true
    cmds:
      - task --version
      - ruby -v
      - echo -n 'rubocop '
      - bundle exec rubocop --version
      - echo -n 'pnpm '
      - npx pnpm --version
      - echo -n 'prettier '
      - npx prettier --version

  dev:
    dir: test-core-fe
    cmds:
      - pnpm install
      - pnpm dev

  test:
    cmds:
      - task: test-core-jobs

  build:
    cmds:
      - task: build-core-base-fe
      - task: build-core-jobs-fe
      # - task: build-core-versions-fe

  test-core-jobs:
    dir: core-jobs
    cmds:
      - bundle exec rake

  build-core-base-fe:
    dir: core-base-fe
    cmds:
      - pnpm install
      - npx pnpm build
    sources:
      - src/**/*.*
      - tsconfig.json
      - vite.config.js
    generates:
      - dist/core-base.js

  build-core-jobs-fe:
    dir: core-jobs-fe
    cmds:
      - pnpm install
      - npx pnpm build
    sources:
      - src/**/*.*
      - tsconfig.json
      - vite.config.js
    generates:
      - dist/core-jobs.js

  build-core-versions-fe:
    dir: core-versions-fe
    cmds:
      - pnpm install
      - npx pnpm build
    sources:
      - src/**/*.*
      - tsconfig.json
      - vite.config.js
    generates:
      - dist/core-versions.js

  create:
    silent: true
    cmds:
      - echo "This will create a new FE module called '{{.CLI_ARGS}}'"
      - echo "COMMAND-C to cancel or any key to continue"
      - read
      - pnpm create vite {{.CLI_ARGS}}-fe --template react-ts
      - cd {{.CLI_ARGS}}-fe && pnpm add --save-peer react react-dom react-admin @mui/material @mui/icons-material
      - cd {{.CLI_ARGS}}-fe && pnpm add -D @faker-js/faker vite-plugin-dts
      - mkdir -p cd {{.CLI_ARGS}}-fe/src/{{.CLI_ARGS}}
      # - BACKEND
      - mkdir {{.CLI_ARGS}}
