# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: versions

  tidy-check:
    cmds:
      - cmd: rubocop **/*.rb **/*.gemspec **/Gemfile
        ignore_error: true
      - npx prettier -c .

  tidy:
    cmds:
      - rubocop -a **/*.rb **/*.gemspec **/Gemfile
      - npx prettier --loglevel warn -w .

  versions:
    silent: true
    cmds:
      - task --version
      - ruby -v
      - echo -n 'rubocop '
      - rubocop --version
      - echo -n 'pnpm '
      - npx pnpm --version
      - echo -n 'prettier '
      - npx prettier --version

  test:
    cmds:
      - task: test-core-jobs

  build:
    cmds:
      - task: build-core-jobs-fe

  test-core-jobs:
    dir: core-jobs
    cmds:
      - bundle exec rake

  build-core-jobs-fe:
    dir: core-jobs-fe
    cmds:
      - npx pnpm build
    sources:
      - src/**/*.*
      - tsconfig.json
      - vite.config.js
    generates:
      - dist/core-jobs.js

  create:
    silent: true
    cmds:
      - echo "This will create a new FE module called '{{.CLI_ARGS}}'"
      - echo "COMMAND-C to cancel or any key to continue"
      - read
      - pnpm create vite {{.CLI_ARGS}}-fe --template react-ts
      - cd {{.CLI_ARGS}}-fe && pnpm add --save-peer react react-dom react-admin @mui/material @mui/icons-material
      - cd {{.CLI_ARGS}}-fe && pnpm add -D @faker-js/faker vite-plugin-dts
      - mkdir -p cd {{.CLI_ARGS}}-fe/src/{{.CLI_ARGS}}
      # - BACKEND
      - mkdir {{.CLI_ARGS}}
