name: Ruby CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        ruby-version: ['3.1', '3.0']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        working-directory: ./core-jobs
        run: bundle install
      - name: Run tests
        working-directory: ./core-jobs
        env:
          DATABASE_URL: 'postgres://postgres:password@localhost:5432/core_test_db'
        run: bundle exec rake
